# 🚀 LEVEL 1: BEGINNER PROJECT
## 🎯 Project: Student Marks Analyzer
🔹 Problem

👉 You have student marks in 3 subjects:

👉 Rows = students

👉 Columns = subjects

In [5]:
import numpy as np
marks = np.array([
    [80, 70, 90],
    [60, 75, 85],
    [90, 88, 92],
    [50, 60, 65]
])

🔥 Tasks
✅ 1. Total marks of each student
✅ 2. Average marks
✅ 3. Find topper (index)
✅ 4. Students scoring > 75 average
✅ 5. Subject-wise average

In [7]:
total_marks = np.sum(marks,axis=1)
total_marks

array([240, 220, 270, 175])

In [11]:
avg = np.mean(marks)
avg

np.float64(75.41666666666667)

In [12]:
total_marks.argmax()

np.int64(2)

In [15]:
avg1 = np.mean(marks,axis=1)
print(avg1)
np.where(avg1>75)

[80.         73.33333333 90.         58.33333333]


(array([0, 2]),)

In [16]:
high = marks[np.mean(marks, axis=1) > 75]
print(high)

[[80 70 90]
 [90 88 92]]


In [18]:
avg2 = np.mean(marks,axis=0)
print(avg2)
np.where(avg2>75)

[70.   73.25 83.  ]


(array([2]),)

# 🚀 LEVEL 2: INTERMEDIATE PROJECT
## 🎯 Project: Salary Data Analyzer
👉 Columns:

* Age
* Salary

In [2]:
import numpy as np
data = np.array([
    [25, 50000],
    [30, 60000],
    [22, 20000],
    [35, 80000],
    [28, 45000]
])

🔥 Tasks
* ✅ 1. Filter salary > 50k
* ✅ 2. Average salary
* ✅ 3. Normalize salary (ML important)
* ✅ 4. Add bonus column

In [3]:
data[data[:,1]>50000]

array([[   30, 60000],
       [   35, 80000]])

In [4]:
np.mean(data[:,1])

np.float64(51000.0)

🔥 “Normalize salary” ka matlab kya hota hai?

👉 Simple words me:

👉 salary ko same scale me convert karna

🔹 Problem kya hoti hai?

👉 Tumhari salaries aisi ho sakti hain:

20000, 50000, 80000

👉 Ye numbers:

bahut bade hain
aur uneven range me hain

👉 ML models ko problem hoti hai ❌

🔥 Solution: Normalization

👉 Hum salary ko aise convert karte hain:

small range → like around -1 to +1

👉 Matlab:

bada number → controlled ho jata hai
sab values comparable ho jati hain
🔹 Actually kya hota hai internally?

👉 Tum:

har value se average (mean) hata dete ho
fir usko spread (std) se divide kar dete ho
🧠 Intuition samjho

👉 Imagine:

mean = center
std = distance/spread

👉 Normalize karne ke baad:

values batati hain:
👉 “ye average se kitni dur hai”
🔹 Example (conceptual)
50000 → average ke paas → near 0  
80000 → average se upar → positive  
20000 → average se niche → negative
🔥 Final Meaning

👉 Normalization =

👉 data ko center + scale karna

🎯 Why important?

👉 ML me:

fast learning
better accuracy
stable training
🧠 One-line understanding

👉 “Normalization means converting data so that it shows how far each value is from the average, in a comparable scale.”

In [33]:
sal = data[:,1]
print(sal)
norm = (sal - np.mean(sal))/np.std(sal)
norm

[50000 60000 20000 80000 45000]


array([-0.05103104,  0.45927933, -1.58196213,  1.47990005, -0.30618622])

In [56]:
bonus = data[:,1]*10/100
np.set_printoptions(suppress=True)
new_data = np.column_stack((data,bonus))
print(new_data)
print(bonus)

[[   25. 50000.  5000.]
 [   30. 60000.  6000.]
 [   22. 20000.  2000.]
 [   35. 80000.  8000.]
 [   28. 45000.  4500.]]
[5000. 6000. 2000. 8000. 4500.]


Q6: Filter age > 25 AND salary > 50k

In [60]:
data[(data[:,0]>25) & (data[:,1]>50000)]

array([[   30, 60000],
       [   35, 80000]])

# 🚀 LEVEL 3: ADVANCED PROJECT
## 🎯 Project: Mini ML Prediction (Linear Model)

In [3]:
import numpy as np
x = np.array([
    [1,2],
    [3,4],
    [5,6]
])

w = np.array([0.5, 1.5])

🔥 Task
✅ Prediction using dot product

In [4]:
y = (x@w)
y = np.dot(x,w)
y

array([ 3.5,  7.5, 11.5])

🔹 Add bias

In [5]:
bias = 2
y = x@w + bias
y

array([ 5.5,  9.5, 13.5])

🔥 TASK 3: Multiple Weights (ADVANCED)

In [8]:
w = np.array([[0.5, 1.5],[1.0,-1.0]])
y = x @ w
y

array([[ 2.5, -0.5],
       [ 5.5,  0.5],
       [ 8.5,  1.5]])

🧠 Meaning

👉 Now model predicts 2 outputs per sample

🔥 TASK 4: Error Calculation

In [9]:
y_true = np.array([4,8,12])
error = y-y_true
print(error)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

🔥 TASK 5: Loss (VERY IMPORTANT)

👉 Mean Squared Error:

loss = mean((y - y_true)^2)

In [10]:
loss = np.mean((y-y_true)**2)
print(loss)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

🧠 What you just learned

👉 This is actual ML pipeline:

input (X)
→ multiply weights (dot product)
→ add bias
→ prediction (y)
→ compare with true (error)
→ compute loss
- adjust w and b

# 🚀 LEVEL 4: PRO PROJECT
## 🎯 Project: Image Processing (VERY COOL 🔥)

👉 Image = 2D array

In [15]:
img = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

🔥 Tasks
✅ Flip image/mirror image change order of value arrangement not shape 
👉 Vertical Flip 

In [16]:
v_flip = img[::-1]
flip

array([[70, 80, 90],
       [40, 50, 60],
       [10, 20, 30]])

In [18]:
h_flip = img[:,::-1]
h_flip

array([[30, 20, 10],
       [60, 50, 40],
       [90, 80, 70]])

✅ Rotate
90 clockwise
🔥 2. Rotate kaise banta hai?

👉 Rotate directly transpose se nahi hota
👉 Transpose + Flip = Rotation

🔥 3. 90° Rotation (Clockwise)

👉 Steps:

Transpose
Horizontal flip

In [29]:
rot = img.T
rot
rot = rot[:,::-1]
rot

array([[70, 40, 10],
       [80, 50, 20],
       [90, 60, 30]])

🔥 4. 90° Anti-clockwise

👉 Steps:

Transpose
Vertical flip

In [35]:
transpose =  img.T
transpose
v_flip = transpose[::-1]
v_flip 

array([[30, 60, 90],
       [20, 50, 80],
       [10, 40, 70]])

👉 Transpose = diagonally flip
👉 Flip = direction fix karta hai
👉 Dono milke = rotation

✅ Brightness increase

In [20]:
bright = img+50
bright

array([[ 60,  70,  80],
       [ 90, 100, 110],
       [120, 130, 140]])

✅ Threshold filter

In [23]:
binary = img[img>50]
binary_idx = img>50
binary
binary_idx

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

👉 Convert to 0 / 255 image

In [24]:
binary_img = np.where(img>50, 255, 0)
print(binary_img)

[[  0   0   0]
 [  0   0 255]
 [255 255 255]]


🔥 TASK 5: Crop Image
👉 Take center part

In [26]:
crop = img[1:,1:]
crop

array([[50, 60],
       [80, 90]])

**🔥 TASK 6: Normalize Image (ML important)**
value / max_value
👉 gives proportion
👉 Normalized value batata hai:

👉 “ye pixel kitna bright hai (percentage me)”

Example
255 → 1.0 (fully bright)
128 → ~0.5 (medium)
0   → 0 (dark)

In [28]:
norm = img/255
print(norm)

[[0.03921569 0.07843137 0.11764706]
 [0.15686275 0.19607843 0.23529412]
 [0.2745098  0.31372549 0.35294118]]
